"""Export a VisiData workspace as a self-contained delivery package.

A delivery package is a directory (or .zip) containing:

    manifest.json   – snapshot manifest (sheets, options, macros, graph state)
    data/           – one data file per sheet (vds, tsv, jsonl, etc.)
    replay.vdj      – full command log for reproducing the session
    README.md       – human-readable description
    start.sh / start.bat  – launcher scripts

All state is produced by the unified snapshot layer (``vd.generate_snapshot``)
in ``visidata/snapshot.py`` so there is no parallel state-keeping path.
"""

import os
import json
import zipfile
import tempfile
import shutil
import stat

from visidata import vd, VisiData, BaseSheet, Path, asyncthread, Progress
from visidata.snapshot import _collect_derived_sheets, SNAPSHOT_VERSION_KEY, SNAPSHOT_ORDER_KEY, SNAPSHOT_SHEETS_KEY


def _write_readme(pkgdir, snap, data_format):
    sheet_names = snap.get(SNAPSHOT_ORDER_KEY, [])
    lines = [
        '# VisiData Delivery Package',
        '',
        f'Generated by {snap.get(SNAPSHOT_VERSION_KEY, "VisiData")}.',
        '',
        '## Contents',
        '',
        f'- Data format: **{data_format}**',
        f'- Sheets ({len(sheet_names)}):',
    ]
    for n in sheet_names:
        lines.append(f'  - `{n}`')
    lines.extend([
        '',
        '## Quick start',
        '',
        '```bash',
        '# Replay the full session (requires VisiData):',
        '  ./start.sh',
        '',
        '# Or open the data directly:',
        '  vd data/',
        '```',
        '',
    ])
    with open(os.path.join(pkgdir, 'README.md'), 'w', encoding='utf-8') as fp:
        fp.write('\n'.join(lines))


def _write_launchers(pkgdir):
    sh_path = os.path.join(pkgdir, 'start.sh')
    with open(sh_path, 'w', encoding='utf-8') as fp:
        fp.write('#!/usr/bin/env bash\n')
        fp.write('set -e\n')
        fp.write('cd "$(dirname "$0")"\n')
        fp.write('if [ -f replay.vdj ] && command -v vd >/dev/null 2>&1; then\n')
        fp.write('  vd -p replay.vdj\n')
        fp.write('elif command -v vd >/dev/null 2>&1; then\n')
        fp.write('  vd data/\n')
        fp.write('else\n')
        fp.write('  echo "VisiData is not installed.  See https://www.visidata.org/"\n')
        fp.write('  exit 1\n')
        fp.write('fi\n')
    st = os.stat(sh_path)
    os.chmod(sh_path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    bat_path = os.path.join(pkgdir, 'start.bat')
    with open(bat_path, 'w', encoding='utf-8') as fp:
        fp.write('@echo off\r\n')
        fp.write('cd /d "%~dp0"\r\n')
        fp.write('where vd >nul 2>&1\r\n')
        fp.write('if %errorlevel%==0 (\r\n')
        fp.write('  if exist replay.vdj (\r\n')
        fp.write('    vd -p replay.vdj\r\n')
        fp.write('  ) else (\r\n')
        fp.write('    vd data/\r\n')
        fp.write('  )\r\n')
        fp.write(') else (\r\n')
        fp.write('  echo VisiData is not installed.  See https://www.visidata.org/\r\n')
        fp.write('  exit /b 1\r\n')
        fp.write(')\r\n')


def _sanitize_filename(name):
    keep = (' ', '.', '_', '-')
    return ''.join(c if c.isalnum() or c in keep else '_' for c in str(name)).strip() or 'sheet'


def _save_data_files(pkgdir, snap, data_format):
    data_dir = os.path.join(pkgdir, 'data')
    os.makedirs(data_dir, exist_ok=True)

    sheets_info = snap.get(SNAPSHOT_SHEETS_KEY, {})
    data_files = {}

    for name in snap.get(SNAPSHOT_ORDER_KEY, []):
        vs = vd.getSheet(name)
        if vs is None:
            continue
        safe = _sanitize_filename(name)
        fn = f'{safe}.{data_format}'
        target = Path(os.path.join(data_dir, fn))
        savefunc = getattr(vs, f'save_{data_format}', None) or getattr(vd, f'save_{data_format}', None)
        if savefunc:
            vd.sync(savefunc(target, vs))
        else:
            vd.warning(f'no save function for format {data_format}, falling back to tsv')
            vd.sync(vd.save_tsv(target, vs))
        data_files[name] = f'data/{fn}'

    return data_files


def _write_replay_vdj(pkgdir, snap):
    from visidata.cmdlog import CommandLogJsonl
    cmdlog_rows = snap.get('cmdlog', [])
    if not cmdlog_rows:
        return
    import visidata
    rows = [vd.cmdlog.newRow(**r) for r in cmdlog_rows]
    cl = CommandLogJsonl('replay', rows=rows)
    target = Path(os.path.join(pkgdir, 'replay.vdj'))
    vd.save_vdj(target, cl)


def _build_manifest(snap, data_format, data_files):
    manifest_sheets = []
    for name in snap.get(SNAPSHOT_ORDER_KEY, []):
        info = snap.get(SNAPSHOT_SHEETS_KEY, {}).get(name, {})
        entry = {
            'name': name,
            'class': info.get('class', 'TableSheet'),
            'data_file': data_files.get(name),
        }
        if info.get('options'):
            entry['options'] = info['options']
        if info.get('columns'):
            entry['columns'] = info['columns']
        if info.get('graph_state'):
            entry['graph_state'] = info['graph_state']
        if info.get('source_sheet'):
            entry['source_sheet'] = info['source_sheet']
        manifest_sheets.append(entry)

    manifest = {
        SNAPSHOT_VERSION_KEY: snap.get(SNAPSHOT_VERSION_KEY),
        'data_format': data_format,
        'sheets': manifest_sheets,
        SNAPSHOT_ORDER_KEY: snap.get(SNAPSHOT_ORDER_KEY, []),
    }
    if snap.get('global_options'):
        manifest['global_options'] = snap['global_options']
    if snap.get('macros'):
        manifest['macros'] = snap['macros']
    return manifest


def _write_manifest(pkgdir, manifest):
    with open(os.path.join(pkgdir, 'manifest.json'), 'w', encoding='utf-8') as fp:
        json.dump(manifest, fp, default=str, indent=2)


def _zip_directory(srcdir, zippath):
    with zipfile.ZipFile(str(zippath), 'w', zipfile.ZIP_DEFLATED, allowZip64=True, compresslevel=9) as zfp:
        for root, _, files in os.walk(srcdir):
            for fn in files:
                full = os.path.join(root, fn)
                arcname = os.path.relpath(full, srcdir)
                zfp.write(full, arcname)


@VisiData.api
@asyncthread
def exportDeliveryPackage(vd, path, scope='current', data_format='vds'):
    """Export workspace as a delivery package.

    *path*
        Directory path (ends with ``/``) or ``.zip`` file.
    *scope*
        ``"current"``, ``"all"``, ``"selected"``, or an iterable of sheets.
    *data_format*
        Extension for the per-sheet data files (``vds``, ``tsv``, ``jsonl``, …).
    """
    path_str = str(path)
    is_zip = path_str.lower().endswith('.zip')

    snap = vd.generate_snapshot(scope=scope, include_cmdlog=True, include_macros=True)

    if is_zip:
        workdir = tempfile.mkdtemp(prefix='vd_pkg_')
    else:
        workdir = path_str
        os.makedirs(workdir, exist_ok=True)

    try:
        data_files = _save_data_files(workdir, snap, data_format)
        _write_replay_vdj(workdir, snap)
        manifest = _build_manifest(snap, data_format, data_files)
        _write_manifest(workdir, manifest)
        _write_readme(workdir, snap, data_format)
        _write_launchers(workdir)

        if is_zip:
            _zip_directory(workdir, path_str)
            vd.status(f'delivery package written to {path_str}')
        else:
            vd.status(f'delivery package written to {workdir}')
    finally:
        if is_zip:
            shutil.rmtree(workdir, ignore_errors=True)


BaseSheet.addCommand('', 'export-delivery-package',
                     'vd.exportDeliveryPackage(inputPath("export delivery package to: ", value=name+".zip"), scope="current", data_format=input("data format [vds/tsv/jsonl/...]: ", value="vds"))',
                     'export current workspace as a self-contained delivery package')

vd.addGlobals({
    'exportDeliveryPackage': exportDeliveryPackage,
    '_collect_derived_sheets': _collect_derived_sheets,
})

vd.addMenuItems('''
    File > Export > delivery package > export-delivery-package
''')
