name: vgit-ci
on:
  pull_request:
    branches:
      - stable
      - develop
  push:
    branches:
      - stable
      - develop

jobs:
  tests:

    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install VisiData with all optional dependencies
      run: python3 -m visidata.dev_cli install all

    - name: Run vgit tests
      run: python3 -m visidata.dev_cli test vgit
